org.gradle.jvmargs=-Xmx4g
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Вшитый в приложение дефолтный TMDb-токен (v4 Read Access Token)
TMDB_ACCESS_TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxMmRjMTcwODBhZDdhMDE0YmVjNzg2NTIzN2Y4NDg2NCIsIm5iZiI6MTc4OTk5OTg5OS4yMjMsInN1YiI6IjZhYjEzYjFiYTE2YWU3NDJjM2M4YmYxOCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.SHtbOk4uUfvCRI6Dvk42vv8zmI_Je2a-FPQEeCceK1Q

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
